import AFTD.Prelude
import AFTD.Kb.Physics.UnitaryOneParameterGroup
import AFTD.Kb.Physics.UnitaryOneParameterGroupInstCoeFunForallRealContinuousLinearMapComplexId
import AFTD.Kb.Physics.UnitaryOneParameterGroupGenerator
import AFTD.Kb.Physics.UnitaryOneParameterGroupAdjointEq

/-!
# UnitaryOneParameterGroup.ofSelfAdjoint

Topic: classical_mechanics   Node: 5a243b01588a

Provenance: formalization of a published result. Source: Physlib, `UnitaryOneParameterGroup.ofSelfAdjoint`. Lean proof by Tom Ole Diem, from https://github.com/leanprover-community/physlib/blob/e411c6e89692e83bc67fe451302ae7f82cf39b10/Physlib/Mathematics/ForMathlib/OneParameterSubgroups/Unitary.lean (Copyright (c) 2026 Tom Ole Diem. All rights reserved, Apache-2.0); 1 verbatim; compiled here.

The unitary one-parameter group generated by a bounded self-adjoint operator.
-/

set_option autoImplicit true in
set_option relaxedAutoImplicit true in
open UnitaryOneParameterGroup in
variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H] in
/-- The unitary one-parameter group generated by a bounded self-adjoint operator. -/
noncomputable def UnitaryOneParameterGroup.ofSelfAdjoint {A : H →L[ℂ] H} (hA : IsSelfAdjoint A) :
    UnitaryOneParameterGroup H := by
  letI : NormedAlgebra ℚ (H →L[ℂ] H) := .restrictScalars ℚ ℂ (H →L[ℂ] H)
  exact {
    toAddChar := {
      toFun t := NormedSpace.exp ((t : ℂ) • (-Complex.I • A))
      map_zero_eq_one' := by simp
      map_add_eq_mul' s t := by
        have hcomm : Commute ((s : ℂ) • (-Complex.I • A)) ((t : ℂ) • (-Complex.I • A)) :=
          ((Commute.refl (-Complex.I • A)).smul_left _).smul_right _
        rw [← NormedSpace.exp_add_of_commute hcomm]
        simp [add_smul, add_comm]
      }
    mem_unitary t := by
      apply NormedSpace.exp_mem_unitary_of_mem_skewAdjoint
      simp [skewAdjoint.mem_iff, hA.star_eq]
    continuous := by
      change Continuous (fun t : ℝ => NormedSpace.exp ((t : ℂ) • (-Complex.I • A)))
      fun_prop
  }
