import AFTD.Prelude
import AFTD.Kb.Tcs.HalvingUpdate
import AFTD.Kb.Tcs.HalvingPredict

/-!
# Halving.mistakes

Topic: learning   Node: 3638f5940f85

Provenance: formalization of a published result. Source: TCSlib, `Halving.mistakes`. Lean proof by Arhaan Aggarwal, from https://github.com/Shilun-Allan-Li/tcslib/blob/c8a02591b1e51faa8cb90dd30cfe2d6a2d5032ea/TCSlib/LearningTheory/MistakeBounds/Halving.lean (Copyright (c) 2026 Arhaan Aggarwal. All rights reserved, Apache-2.0); 1 verbatim; compiled here.

$\mathtt{mistakes}(\mathtt{eval}, \mathtt{target}, V, xs)$ is the total number of
prediction errors made by the Halving Algorithm when it processes the input list $xs$,
using the version space $V$, with the true label at each step supplied by
$\mathtt{target}$.  It is defined recursively: the empty list yields zero mistakes, and
for a list $x :: xs$ the count is $1$ if the algorithm mispredicts on $x$ (else $0$),
plus the mistakes on the remainder using the updated version space.
-/

set_option relaxedAutoImplicit false in
set_option autoImplicit false in
variable {Hyp X : Type*} in
/-- The number of mistakes the Halving Algorithm makes when run from the version space `V` over the finite list of inputs `xs`, with every label generated by the hypothesis `target` (the label of `x` is `eval target x`). At each input the algorithm predicts with the current version space, incurs one mistake if that prediction differs from the target's label, and then updates the version space with the observed label before moving to the next input. [MRT18, §8.2.1 (Halving algorithm)]; origin [Lit88, §3]. -/
def Halving.mistakes (eval : Hyp → X → Bool) (target : Hyp) (V : Finset Hyp) :
    List X → ℕ
  | [] => 0
  | x :: xs =>
      let y := eval target x
      let V' := update eval V x y
      (if predict eval V x = y then 0 else 1) + mistakes eval target V' xs
