import AFTD.Prelude

-- game_theory_economics
import AFTD.Kb.GameTheoryEconomics.CondorcetWinner
import AFTD.Kb.GameTheoryEconomics.CondorcetWinnerUnique
import AFTD.Kb.GameTheoryEconomics.DirectMechanism
import AFTD.Kb.GameTheoryEconomics.IsBlockingPair
import AFTD.Kb.GameTheoryEconomics.IsDominantStrategyIncentiveCompatible
import AFTD.Kb.GameTheoryEconomics.IsPureNashEquilibrium
import AFTD.Kb.GameTheoryEconomics.IsStableMatching
import AFTD.Kb.GameTheoryEconomics.IsStableMatchingOfNoStrictPreference
import AFTD.Kb.GameTheoryEconomics.MarriageMarket
import AFTD.Kb.GameTheoryEconomics.NotIsStableMatchingOfUniversalPreference
import AFTD.Kb.GameTheoryEconomics.NotPureNashOfExistsBetterResponse
import AFTD.Kb.GameTheoryEconomics.PureNashOfCommonPayoffMaximizer
import AFTD.Kb.GameTheoryEconomics.StableMatchingNotPrefOfPref
import AFTD.Kb.GameTheoryEconomics.StableMatchingOfAllMenTopChoice
import AFTD.Kb.GameTheoryEconomics.StableMatchingOfAllWomenTopChoice
import AFTD.Kb.GameTheoryEconomics.StrategicGame

-- physics
import AFTD.Kb.Physics.BoltzmannDistribution
import AFTD.Kb.Physics.CanonicalPartitionFunction
import AFTD.Kb.Physics.IsHamiltonianTrajectory
import AFTD.Kb.Physics.IsHamiltonianTrajectoryZero
import AFTD.Kb.Physics.IsLorentzMatrix
import AFTD.Kb.Physics.IsLorentzMatrixMul
import AFTD.Kb.Physics.IsLorentzMatrixOne
import AFTD.Kb.Physics.KleinGordonEquation1D
import AFTD.Kb.Physics.KleinGordonZeroMassIffWaveEquation
import AFTD.Kb.Physics.MinkowskiMatrix
import AFTD.Kb.Physics.PoissonBracket
import AFTD.Kb.Physics.PoissonBracketAnticomm
import AFTD.Kb.Physics.QuantumCommutatorSelfAdjointSkew
import AFTD.Kb.Physics.QuantumProjectionExpectationNormSq
import AFTD.Kb.Physics.QuantumUnitaryPreservesInner
import AFTD.Kb.Physics.WaveEquation1D

-- tcs
import AFTD.Kb.Tcs.BinaryTreeNumLeavesLePowHeight
import AFTD.Kb.Tcs.BooleanCircuit
import AFTD.Kb.Tcs.BooleanCircuitEval
import AFTD.Kb.Tcs.BooleanCircuitEvalDemorganAnd
import AFTD.Kb.Tcs.BooleanCircuitEvalNotNot
import AFTD.Kb.Tcs.CardSimpleGraph
import AFTD.Kb.Tcs.CircuitGate
import AFTD.Kb.Tcs.ClassClosedUnderComplIffEqCo
import AFTD.Kb.Tcs.ClassEqCoIffSubsetCo
import AFTD.Kb.Tcs.ClassEqCoOfClassEq
import AFTD.Kb.Tcs.ClassSubsetInterCoOfEqCo
import AFTD.Kb.Tcs.CnfEmptySatisfiable
import AFTD.Kb.Tcs.CnfLit
import AFTD.Kb.Tcs.CnfResolutionSoundness
import AFTD.Kb.Tcs.CnfSatisfiable
import AFTD.Kb.Tcs.CnfSatisfiableAppendSumIff
import AFTD.Kb.Tcs.CnfSatisfiableOfAppend
import AFTD.Kb.Tcs.CnfSatisfiableSubset
import AFTD.Kb.Tcs.CnfSingleClauseSatisfiableIff
import AFTD.Kb.Tcs.CoClass
import AFTD.Kb.Tcs.CoClassInvolutive
import AFTD.Kb.Tcs.CoClassMonotone
import AFTD.Kb.Tcs.ComparisonSortDecisionTreeHeightGe
import AFTD.Kb.Tcs.ComparisonSortHeightGeHalfNLogbHalfN
import AFTD.Kb.Tcs.DeciderClassEqCo
import AFTD.Kb.Tcs.DivideAndConquerEqualRootsRecurrence
import AFTD.Kb.Tcs.DivideAndConquerMergesortRecurrence
import AFTD.Kb.Tcs.DivideAndConquerRecursionTree
import AFTD.Kb.Tcs.DivideAndConquerUnequalRootsRecurrence
import AFTD.Kb.Tcs.ExistsFamilyCardSixNoThreePetalSunflower
import AFTD.Kb.Tcs.ExistsNotMemOfSumCardLt
import AFTD.Kb.Tcs.ExistsTwoColoringOfCardMulTwoLtTwoPow
import AFTD.Kb.Tcs.ExpTimeBounded
import AFTD.Kb.Tcs.FactorialGeHalfPowHalf
import AFTD.Kb.Tcs.GateType
import AFTD.Kb.Tcs.GraphMatchingEncardLeVertexCoverEncard
import AFTD.Kb.Tcs.GraphMatchingNum
import AFTD.Kb.Tcs.GraphMatchingNumBot
import AFTD.Kb.Tcs.GraphMatchingNumLeEncardEdgeSet
import AFTD.Kb.Tcs.GraphMatchingNumLeVertexCoverNum
import AFTD.Kb.Tcs.GraphMatchingNumMono
import AFTD.Kb.Tcs.IsRegularDiff
import AFTD.Kb.Tcs.IsRegularIffEnfa
import AFTD.Kb.Tcs.IsRegularIffNfa
import AFTD.Kb.Tcs.IsRegularKstar
import AFTD.Kb.Tcs.IsRegularLeftQuotient
import AFTD.Kb.Tcs.IsRegularMul
import AFTD.Kb.Tcs.IsRegularSymmDiff
import AFTD.Kb.Tcs.IsRegularZero
import AFTD.Kb.Tcs.IsSunflower
import AFTD.Kb.Tcs.IsSunflowerCoreUnique
import AFTD.Kb.Tcs.IsSunflowerEmptyCoreIffPairwiseDisjoint
import AFTD.Kb.Tcs.IsSunflowerMono
import AFTD.Kb.Tcs.KarpReducible
import AFTD.Kb.Tcs.ManyOneReducibleCompl
import AFTD.Kb.Tcs.MasterTheoremPolynomialCaseOne
import AFTD.Kb.Tcs.MasterTheoremPolynomialCaseThree
import AFTD.Kb.Tcs.NPHard
import AFTD.Kb.Tcs.NfaAcceptsIsRegular
import AFTD.Kb.Tcs.NondeterministicPolyTimeBounded
import AFTD.Kb.Tcs.NotComputableOfManyOneReducible
import AFTD.Kb.Tcs.NotReComplOfReAndNotComputable
import AFTD.Kb.Tcs.NotReOfManyOneReducibleAndNotRe
import AFTD.Kb.Tcs.PairEncode
import AFTD.Kb.Tcs.PairEncodeInjective
import AFTD.Kb.Tcs.PolyTimeBounded
import AFTD.Kb.Tcs.PolyTimeSubsetExpTime
import AFTD.Kb.Tcs.REComplete
import AFTD.Kb.Tcs.ReCompleteOfLe
import AFTD.Kb.Tcs.ReOfManyOneReducible
import AFTD.Kb.Tcs.RePredAnd
import AFTD.Kb.Tcs.RePredOr
import AFTD.Kb.Tcs.SauerShelahCardLeMulPow
import AFTD.Kb.Tcs.SauerShelahCardLeSumChoose
import AFTD.Kb.Tcs.SchwartzZippelExistsNonzeroEval
import AFTD.Kb.Tcs.SchwartzZippelZeroCountLe
import AFTD.Kb.Tcs.SelfHaltingComplNotRe
import AFTD.Kb.Tcs.SelfHaltingProblemRe
import AFTD.Kb.Tcs.SelfHaltingProblemUndecidable
import AFTD.Kb.Tcs.TimeBounded
import AFTD.Kb.Tcs.TimeBoundedEqCoOfDeciderNegationClosed
import AFTD.Kb.Tcs.TimeBoundedMono
import AFTD.Kb.Tcs.VertexCoverNumAddIndepNum
